### ISSUE TITLE
Need way to delete a song

### ISSUE THREAD

**Issue by kauffecup** [kauffecup/HangsDB#23]
- [ ] mysql api
- [ ] ui

**Comment by ghost** [comment]
I'm gonna make it so deleting a song automatically deletes all the junction entries for that song. Let me know if you don't want that.

**Comment by ghost** [comment]
Okay this is going to be tedious and take forever because of the way I made the database. I set things up so you can't delete something if it's being referenced in a junction table (the other option is to auto delete references to the thing you're deleting, that's what we want). It's really annoying to do, I'm gonna put that on the back burner (still will happen by AC meeting though).
